echo = input("Enter text here:")
print(echo)
number = int(input("Enter a number:"))
print(number + 1)
number_float = float(input("Enter a number:"))
print(number_float + 0.5)
add_float = float(input("Enter a number:"))
add_float2 = float(input("Enter another number:"))
print(f"The sum is {add_float + add_float2}")
multiply_float = float(input("Enter a number:"))
multiply_float2 = float(input("Enter another number:"))
print(f"The product is {multiply_float * multiply_float2}")
divide_int = int(input("Enter a number:"))
divide_int2 = int(input("Enter another number:"))
print(f"The result is {divide_int / divide_int2}")
